### PR TITLE
Implemented localization / translation

### PR DESCRIPTION
**Pull request by dgallinari**
We changed all the hard-coded strings (on frontend yet) to use the trans() method and also added the translation strings for pt-BR language.

Please let us know if you need anything differently implemented.

We'll be working on the backend on the next days as well.

Thanks in advance!
Best regards,
<a href="http://www.descubraomundo.com" target="_blank">Descubra o Mundo</a> IT Team

### CODE REVIEW

**Comment by dgallinari** [comment]
Hello @rappasoft 

We've finished to translate both frontend and backend now. They are all commited in this pull request.

Let me know if you think this is an interesting feature.
Thanks in advance!
Best regards,
Daniel
<a href="http://www.descubraomundo.com" target="_blank">Descubra o Mundo Intercâmbios</a>

**Comment by rappasoft** [comment]
Holy wow. Give me a few to go through it all but i'm sure it's fine. Great work! Its contributors like you that make me want to keep up support in light of the upcoming laravel releases.

**Comment by dgallinari** [comment]
Thanks! Great to hear that :)

We loved your project btw. It helped us a lot and saved a lot of development time from our team.

We are starting a development sprint right now using laravel-5-boilerplate as base and if we identify anything that would make sense to commit as an enhancement on this fork, we'll do so :)

Thanks again for your quick reply and let us know if there is something we can help you on.

Best regards,
Daniel

**Comment by rappasoft** [comment]
Everything worked fine just moved the welcome view into a lang folder and updated the includes.

**Comment by dgallinari** [comment]
Great! I'll pull your updates for our fork :)

Thanks and count on us! =)

**Pull request merged**
