### PR TITLE
Updated .env.example social default values

### PR DESCRIPTION
**Pull request by jericopulvera**
This pr improves the default .env.example social credentials for easier socialite setup.

### CODE REVIEW

**Comment by rappasoft** [comment]
Why are you turning them all on though?

**Comment by jericopulvera** [comment]
It is commented so it is the same as false.

**Comment by rappasoft** [comment]
Ah true true ill merge on next release

**Comment by jericopulvera** [comment]
Do you think it's better to just remove the comment and set the active value to false. 

What do you think?

**Pull request merged**
