### PR TITLE
Fixed Spanish Translations on Boilerplate v3.1.4

### PR DESCRIPTION
**Pull request by poseso**
Fixed Spanish Translations from boilerplate v3.1.4 and added on lang history  'recent_history' => 'Recent History'  to avoid hardcoded text under views\backend\dashboard.blade.php -> Line: 25

### CODE REVIEW

**Comment by rappasoft** [comment]
Thanks but why are all the file permissions changed?

**Comment by poseso** [comment]
What do you mean?

**Comment by poseso** [comment]
oh! i don't know how that commit came  e4bde48  <- im trying to delete it but it's not letting me

**Comment by poseso** [comment]
you mean this 100644 → 100755  ?

I usually use this permissions working locally

**Comment by poseso** [comment]
Could it be that i did the pull request from my mac?

**Comment by rappasoft** [comment]
I guess its not a big deal since when they went to production they should rewrite themselves.

On my servers directories are 775 and files are 664.

**Comment by poseso** [comment]
ah ok, well in case you need me to do anything else just let me know

**Comment by rappasoft** [comment]
Can you add the timeout/mins strings to the other languages?

**Comment by poseso** [comment]
sure no problem, im looking through all the files to see if they need anything else

**Comment by poseso** [comment]
I guess there is no more translations left

**Comment by poseso** [comment]
by the way, i just realized that the permissions of the files only changes when i create pull requests within my mac, when i do it  with my windows laptop they dont change

**Comment by rappasoft** [comment]
Yeah im not too worried about it because its the job of the developer to make sure they're all right when uploaded.

**Comment by rappasoft** [comment]
It should be good will merge in shortly thank you!

Anthony Rappa

**Comment by poseso** [comment]
You welcome Anthony

**Comment by rappasoft** [comment]
It should be good will merge in shortly thank you!

Anthony Rappa

**Pull request merged**
