### PR TITLE
Replace glob() function usage

### PR DESCRIPTION
**Pull request by mikimaine**
Since glob() function have unexpected output in some systems it is probably a good idea to replace it with more consistent one (recursiveDirectoryIterator & recursiveIteratorIterator).

This is a fix. Form the official php glob() description it is known that the function have unexpected behaviors like :  

> On some systems it is impossible to distinguish between empty match and an error.

> This function isn't available on some systems (e.g. old Sun OS).

>  The GLOB_BRACE flag is not available on some non GNU systems, like Solaris.

So i have created this function with the more appropriate method to avoid this and other similar issues.

[PHP glob() doc](http://php.net/manual/en/function.glob.php)

### CODE REVIEW

**Comment by rappasoft** [comment]
Cool thanks!

**Comment by rappasoft** [comment]
This makes the tests blow up. Can you update the tests?

**Comment by mikimaine** [comment]
OK I will .

**Comment by mikimaine** [comment]
@rappasoft now the test is passing. can be merge.

**Pull request merged**
