### PR TITLE
fix for carbon and php localization regarding dates

### PR DESCRIPTION
**Pull request by blomdahldaniel**
This solves #211
Enables localized `diffForHumans()` and `Carbon::now()->formatLocalized()`

# Report on locales
I feel that there is a lot to talk about when it comes to this. Therefore I have tried to gather some info on the subject and try to explain why this is important and how it works.
I have also done some research on language standards for you to take a stand on for the future.

#### What does setLocale() and Carbon::setLocale() do?
**I took french as the example:**
1. Carbon diffForHumans() - **il y a 10 heures** (10 hours ago)
2. Carbon::now()->formatLocalized('%e %B') - **8 janvier** (8 January)

**Solution**
1. `Carbon::setLocale('fr');`
2. `setLocale(LC_TIME, 'fr_FR');` (see [Carbon Docs](http://carbon.nesbot.com/docs/#api-localization))

### 1. Carbon
Carbon uses the ISO-639 standard (**ISO-639-1** to be exact).
[List of ISO-639 locale codes](http://www.loc.gov/standards/iso639-2/php/code_list.php)

**Examples**
* `en` - English
* `fr` - French
* `sv` - Swedish

### 2. PHP
PHP uses the GNU C Library formatting for locale codes. It combines languages and regions to enable more specific libraries. It also uses the **ISO-639-1** for both the *language* and the *region* codes. Language is separated with `_` from region and the region is spelled with capitals.
[List of GNU locale codes](http://lh.2xlibre.net/locales/)

**Examples** *language_REGION*
* `en_US` - English - United States
* `fr_FR` - French - France
* `fr_CH` - French - Switzerland
* `sv_SE` - Swedish - Sweden

--------------------------------------------------------------------------------
# Consideration
1. What standard should this boilerplate follow regarding naming of folders and key name in the `$languages` array?

### 1. Diversity
To enable more specific translations the combined *language* + *REGION* system is great.
However, now that we have to follow PHP GNU C Library formatting in one case, I think we should use that standard also in the folder names when necessary. *When necessary* I mean with languages that possibly could have multiple regions that wants an translation for example Portuguese, Spanish and French.

##### Pros And Cons
**Pros**
1. Great possibilities to grow and have very specific languages
**Cons**
1. Honestly, possibly a whole lot of poorly updated language packages
2. one pretty ugly array..
```
protected $languages = [
    'en' => ['en', 'en_US'],
    'es_ES' => ['es', 'es_ES'], (spanish - Spain)
    'es_AR' => ['es', 'es_AR'], (spanish - Argentina)
    'fr_FR' => ['fr', 'fr_FR'],
    'pt_BR' => ['pt', 'pt_BR'], (Portuguese - Brazil)
    'pt_PT' => ['pt', 'pt_PT'], (Portuguese - Portugal)
    'sv' => ['sv', 'sv_SE'],
];
```

### 2. Lets be real
Say screw it and only allow one translation per language. Because sure, this repo is getting bigger but it doesn't need to be that language specific? Let's not get things overly complicated?

##### Pros And Cons
**Pros**
1. More simple and slick folder structures
2. More likely to be updated better while less languages
3. A darn fine and easy to manage `$languages` array
**Cons**
1. lost posibility of specific languages
2. Small refactor needs to be done:
* Rename all occurrences of `fr-FR``
. 
* Refactor the `LocaleMiddleware` a litle
```
protected $languages = [
    'en' => 'en_US',
    'es' => es_ES',
    'fr' => 'fr_FR',
    'pt' => 'pt_PT',
    'sv' => 'sv_SE',
];
```
--------------------------------------------------------------------------------

What do you say?
I would say option 2 and then good night to you good sir.

### CODE REVIEW

**Comment by rappasoft** [comment]
I applaud your research and will go through it throughly probably tomorrow and test it on my local version. I'm all for what's cleaner but also what will prevent me from having to refactor in the future. I want it to be easy for people to contribute language packs, which means option 2 is probably the cleanest.

The only thing I'm worried about is for example when having 1 pack for all, people from (spanish - Spain) making a PR to change it because it's wrong for them because its set for (spanish - Argentina). Then there will be PR's back and forth for the same language pack because theirs different dialects. 

If that ends up being a problem it would mean theres a shit ton of people using this. I honestly have no idea how many people currently use it.

I'm really glad you had the time to research, because i've been researching the timezone issues.

There are all things that we take for granted when using online services because they always seem to have all this stuff, and I never bothered to see if there was a norm or how they did it.

Eventually I hope to have this be such a solid complete solution as a starting point for not only myself, but everyone. A good thousand hour head start at this point.

**Comment by blomdahldaniel** [comment]
I almost think this boils down to a decision from you. What signals you want this Boilerplate to send. My hones opinion is that I do not think that it should/could be that big of a problem if we only us `fr` and `es`. 

But if you want to keep it all 100% flexible I cant blame you. But for the sake of consistency you might apply the *language + REGION* system for all the languages directories (just like the latest issue talked about). And because of the PHP GNU C library you could name the  folders with the same separator,  `_` ?
```
resources/lang/
    en_US/
    sv_SE/
    fr_FR/
    es_ES/
// etc....
```

It is a bit funny how the entire boilerplate talks about the locale stuff now, namings, language codes and stuff. Haha! :D kind of cool to see so much interest. :)

Let me know when you have taken a look at this and comes to conclusion.

**Comment by blomdahldaniel** [comment]
## Big question though
Setting the language in the `session()` is not a great way of doing it in my honest opinion. It doesn't take long before the session is lost and the language defaults back to english. Maybe about 6 hours or something is my experience with it now. Is it possible to store cookies on the user end without a cookie service/driver?

**Comment by error500** [comment]
I would say cookies for guest users and database for identified users

**Comment by rappasoft** [comment]
Been swamped with work but I promise i'll get to these soon.

**Comment by blomdahldaniel** [comment]
@rappasoft no stress bro!

**Comment by blomdahldaniel** [comment]
This was a quick and dirty fix for this issue. I think we hav come up with a great solution now. So I will close this out.

**Pull request closed without merging**
