### PR TITLE
Added travis-ci & coveralls

### PR DESCRIPTION
**Pull request by linzhengen**
Hi, This pull request added `travis-ci` to execute phpunit & coverage, upload the code coverage to `coveralls.io`

# task
- [x] add travis-ci setting into travis.yml
- [x] add satooshi/php-coveralls php package
- [x] add coveralls setting into travis.yml
- [x] fix PHP Fatal error when execute phpunit coverage 

# need to add repository to build job
https://travis-ci.org/
https://coveralls.io/

## why changed Breadcrumbs directory to  `routes/Breadcrumbs`
Laravel Breadcrumbs Document  https://laravel-breadcrumbs.readthedocs.io/en/latest/start.html#define-your-breadcrumbs
```
[vagrant@localhost wwwroot]$ ./vendor/bin/phpunit --coverage-clover=coverage.clover
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught Error: Class 'Breadcrumbs' not found in /var/wwwroot/app/Http/Breadcrumbs/Backend/Access/User.php:3
```

### CODE REVIEW

**Comment by rappasoft** [comment]
Very nice. Going to take me a few days to test.

**Comment by rappasoft** [comment]
Can someone do a quick explanation of the travis.yml and coveralls.yml files as I am unfamiliar with both services?

**Comment by linzhengen** [comment]
@rappasoft 
Sorry for the lack of explanation of travis.yml and coveralls.yml

### About coveralls.yml
coveralls.yml is a configure options file for `satooshi/php-coveralls` php package
see document https://github.com/satooshi/php-coveralls#coverallsyml

### About travis.yml
It can customize any step in this process in `.travis.yml`
see document https://docs.travis-ci.com/user/customizing-the-build

phpunit is executed in this matrix

|           | env1(mysql)  | env2(pgsql)  | env3(mysql for coverage) | env4(sqlite)   |
|:---------:|--------------|--------------|--------------------------|----------------|
| php5.6    | must success | must success | exclude                  | allow failures |
| php7.0    | must success | must success | exclude                  | allow failures |
| php7.1    | must success | must success | exclude                  | allow failures |
| php7.0.12 | --           | --           | include(allow failures)  | --             |

**Comment by rappasoft** [comment]
Ah ok cool thanks. I have it hooked up and working.

**Comment by rappasoft** [comment]
It seems coveralls isn't firing on master, I do have a development badge though on coveralls.io, but I can't figure out how to get it to run on master. It should have run with travis right?

**Comment by linzhengen** [comment]
I think that is auto build no need to set it to run on master.

But, I found this error log on master and .
master branch https://travis-ci.org/rappasoft/laravel-5-boilerplate/jobs/230342027#L650
development branch https://travis-ci.org/rappasoft/laravel-5-boilerplate/jobs/230488418#L511

I will create new pull request after examining this problem.

**Pull request merged**
