### PR TITLE
added hebrew locale

### PR DESCRIPTION
**Pull request by rijensky**
Hebrew locale added.
If anything is missing or wrong for any reason, feel free to contact me and I'll fix it asap.
Thanks. :)

### CODE REVIEW

**Comment by rappasoft** [comment]
Where are the language files?

**Comment by rijensky** [comment]
resources/lang/he...
I think I don't understand the question.

**Comment by rijensky** [comment]
oh whoops, I do understand the question XD
sorry, commiting right up.

**Comment by rappasoft** [comment]
Your commit only has menu file changes, not the actual language files: https://github.com/rappasoft/laravel-5-boilerplate/pull/1003/files

**Comment by rappasoft** [comment]
Awesome thanks

**Comment by rijensky** [comment]
Done.
Sorry about that, this is my first pull request.
I usually work alone :)

**Comment by rijensky** [comment]
Thank you!

**Pull request merged**
