### PR TITLE
add missing vue dependency in backend

### PR DESCRIPTION
**Pull request by damieneskimo**
# Enhancement
This PR is to add Vue as a dependency in the backend, which can allow users to use Vue.js in the backend out of the box.

### CODE REVIEW

**Comment by bambamboole** [comment]
I think Vue should not be mounted on the body.

**Comment by damieneskimo** [comment]
@bambamboole Yes You are right. I have added a wrapping div. Can you please check whether it is OK? Thanks

**Comment by rappasoft** [comment]
This is already included in the frontend js, there are no vue components in the backend hence my not loading it.

**Comment by damieneskimo** [comment]
Fair enough. I will close the ticket then.

**Pull request closed without merging**
