### PR TITLE
Small tweak for Javascript Injected from a Controller

### PR DESCRIPTION
**Pull request by poseso**
Translation for Javascript injected from a controller under FrontendController and strings for all languages, some languages needs translation so it will appear in english.

### CODE REVIEW

**Comment by rappasoft** [comment]
The only reason i'm hesitant to merge this is 10/10 people are going to have to remove it from 10 files now you know? No one is going to keep that little bit of example lol.

**Comment by poseso** [comment]
hahah

**Comment by rappasoft** [comment]
Some things I need to let go but thanks!

**Comment by vernard** [comment]
5/7 for the effort. lol

**Pull request closed without merging**
