### PR TITLE
Added reCAPTCHA to Login Screen

### PR DESCRIPTION
**Pull request by poseso**
I added reCAPTCHA to the login screen, since i don't only use it in registration form, so this way we have it on the login and register form, activated via env

### CODE REVIEW

**Comment by rappasoft** [comment]
Don't often see it on login screens though?

**Comment by poseso** [comment]
well, at least in my country almost all systems has it, but if you think it shoudn't be in there it's ok

**Comment by rappasoft** [comment]
Do you use it to help against brute force attacks or something?

**Comment by poseso** [comment]
yes, specially for brutefoce attacks, i use it to prevent automated attacks

**Comment by rappasoft** [comment]
Maybe it should be something that only pops up after X login failures?

**Comment by poseso** [comment]
it could pop up after 3 failed attemps, then we can store the email/username and the IP address for the login attemps in a db table or count how many times the form is submitted for an IP address? and then show the captcha ?

**Comment by rappasoft** [comment]
I've come up with a solution that works nicely, let me know what you think: https://github.com/rappasoft/laravel-5-boilerplate/commit/108a49817b29daa828cb479c6e2f8056cc4673a3

**Comment by poseso** [comment]
very nice solution, better than what i was thinking of..

**Comment by rappasoft** [comment]
It's working nice on my end. Let me know if you have time to try. I tried like 10 other ways before I got to this point.

**Comment by poseso** [comment]
let me try it out and let you know soon...

**Comment by poseso** [comment]
Yes, is working perfectly.

**Comment by rappasoft** [comment]
Awesome. I'll merge it in.

Thanks!

**Pull request closed without merging**
