### PR TITLE
Quick'n dirty suggestion for new dashboard and profile management

### PR DESCRIPTION
**Pull request by blomdahldaniel**
Suggestion from me in #485 
# This PR is not suposed to be merged
This is a dirty and quick way for me to suggest some changes around the dashboard and UX in whole. **Some restructuring has to be don but its not that much.** That would be the next thing to talk about.

Also, I think its a good idea to provide a suggested "wireframe" for the dashboard but the one I suggested here should probably be fine tuned some more first. Or maybe it should just be blank?

### Changes:
* Remove `Home` from navbar (feels redundant, instead link to `/` on logo)
* Add `Dashboard` to navbar
* Remove `Dashboard` from navbar dropdown
* Reorder navbar dropdown
* Restructure `Dashboard view` and added placehold.it as to help the developers se the potential view
  * Suggest application specific data in dashboard
  * Display small user area with link to "My profile" or "Settings"
* Add new route "My Profile" or "Settings" route:`/profile` `name('frontend.profile.index')` might be changed to `show` instead?
* create tabs for profile view. Made http-request to change the view instead of javascript
  1. Profile
  2. Change Password
* Add fa-save to buttons
skarmavbild 2016-10-12 kl 13 09 07
skarmavbild 2016-10-12 kl 13 10 27
skarmavbild 2016-10-12 kl 13 10 42

### CODE REVIEW

**Comment by rappasoft** [comment]
Going to start adding some of this today.

**Comment by blomdahldaniel** [comment]
Yummy! Let me know If you want me to do some of the parts!

**Comment by rappasoft** [comment]
I actually added quite a bit of it.

**Comment by blomdahldaniel** [comment]
Looks really good imo!
Just want to add "Edit Information" as a tab as well. Just like "Change Password" ?

**Comment by rappasoft** [comment]
I'm not a huge fan of too many open forms on one page, I think change password is an exception.

**Comment by blomdahldaniel** [comment]
That was actually why I aded the "fake tabs". So that the tabs had a separate page and then only one form on each page.

Don't you think that the whole idea falls apart if you don't go all in for consistently?
At least in my head that is not desired UX.

**Comment by rappasoft** [comment]
I don't think I fully understand what you mean

**Comment by rappasoft** [comment]
I took a stab it with my latest commit: https://github.com/rappasoft/laravel-5-boilerplate/commit/b130c02d4966f4b47e33d64af64d07c62cdeb8e7

**Comment by rappasoft** [comment]
Let me know if i've accomplished enough to take this off my plate.

**Comment by blomdahldaniel** [comment]
By just looking at the code from mobile I think it's nice and the right choice. 

Sorry for being unclear: 
In this verry PR, the tabs was actually not changed with javascript. It was changed with server reload. Good old a tag, there is bootstrap support for that functionality. So,  that way, each tab was a separate blade file = only one form per page since that was an issue for me as well! 

I dont want to put these things over you. Once v4 is released it will be easier to make PRs for things like this. I think the UX is getting to a sweet spot in this project! Glad you took your time. This is getting big man! Youve got a GitHub repo with almost 1.7k stars!! So cool actually! You can be proud man!! 😀😀 hope you can feel that in the swamp of issues.

**Pull request closed without merging**
