### PR TITLE
Update Test Suite and remove Browserkit Dependency

### PR DESCRIPTION
**Pull request by bambamboole**
Hi @rappasoft,

first of all, this is a very nice project. I really appreciate you

I'm new to open source and read your message that it is hard to maintain such a package.
So maybe I can help you a bit :-)

This PR will refactor the Test Suite to latest Laravel Conventions and remove Browserkit Dependency.
 

This PR add a line in `phpunit.xml` that the `MAIL_DRIVER` is set to `log` that the tests do not fail initially.

Also I changed the language switch route to not call the method `swap` on the `LanguageController` but invoke it via `__invoke`.

cheers
bambamboole

### CODE REVIEW

**Comment by rappasoft** [comment]
Why don't you like browser kit? It makes it easier to understand what's going on and faster overall to make tests.

**Comment by bambamboole** [comment]
I think it would be cleaner to use built in stuff. This is also the way the official laravel docs describe how to write tests. 
I would also recommend to sort tests in feature and unit tests and resort them a bit for a better overview.
The result would be an updated easy to extend test suite.

**Comment by bambamboole** [comment]
So until now All Tests are refactored to use the default TestCase and Browserkit as dependency is removed.

**Comment by bambamboole** [comment]
This PR also solves Issue #979 .

**Comment by rappasoft** [comment]
You can go ahead and do what you stated above, after that I will give it a thorough look over. Good work.

**Comment by bambamboole** [comment]
@rappasoft , I've refactored all tests.
Now there are less tests and assertions. They are more explicit and (in my opinion) better sorted, because each Feature has its own Test Class.

Another change is, that I avoided to assert against to see something on the page, because changing the layout would maybe break the tests. Instead I asserted against the flash messages in the session and used the translations so that there was no need to set a language in the tests.

Additionally I never used the setUp method, so each tests builds up the stuff its need. I only declared a loginAsAdmin method on the TestCase because that would be some kind of cumbersome to write this in each test.

There are not as much tests like before, but I also think they are faster than before.

At least I have to say that I think not every use case is tested, but almost. While refactoring the test case I got a very good insight of the code. Really looking forward to make more PR's to help you.

**Comment by rappasoft** [comment]
This is crazy. Can't wait to review it all. If you have time I could use help with the issues list too. Would be appreciated.

**Comment by bambamboole** [comment]
@DrPandalot thanks!

I think we don't need an .env.testing file because all envvars which need to be changed for the tests are declared in phpunit.xml.

I fixed the broken tests. I was sure that all tests were passing... Now all are passing :-)

**Comment by bambamboole** [comment]
The last commits were an accident while playing with Jenkins. Sorry for that...

**Pull request merged**
