### PR TITLE
Fix `Cannot find module 'babel-preset-env'`

### PR DESCRIPTION
**Pull request by belzaaron**
# Fixes
The `Error: Cannot find module 'babel-preset-env'` error thrown when you have a fresh install of the repo (though `yarn` was run and completed, error free). Next running `npm run dev` would produce this error. Again, this fixes it; without any new dependencies-just namespacing updates.

I also compiled the assets using `production` script as a failsafe.

### CODE REVIEW

**Comment by thigarette** [comment]
This worked beautifully. Thanks for the help!

**Comment by taoufiqaitali** [comment]
worked for  me thanks

**Comment by ozgurkalan** [comment]
Same issue:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
```
babel-preset-env solved the problem.

**Comment by WesleyMarz** [comment]
This fixes the issue, thanks. Unfortunately this also breaks vue example component it fails to load on frontend.

**Comment by belzaaron** [comment]
@WesleyMarz check PR #1180

**Comment by lukecurtis93** [comment]
thanks for this - hope this is merged soon.

**Pull request merged**
