### PR TITLE
Enhancement build, structure and fix jest tests

### PR DESCRIPTION
**Pull request by rivajunior**
# Is this a fix, enhancement or language pack?
This is both, fix and enhancement.

On this pull request I've made the following changes:

* [Changed](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/resources/sass/frontend/app.scss#L5) `_custom.scss` for `_variables.scss`, how [Laravel uses](https://github.com/laravel/laravel/tree/master/resources/sass)

* [Added Fontawesome web](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/package.json#L19) on [scss](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/resources/sass/frontend/app.scss#L18) to remove Fontawesome SVG used on JS, because it doesn't work on old browsers since Mix isn't processing `node_modules` dependencies. (Plus: build size gets lighter)

* Simplified [.babelrc](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/.babelrc) putting [browserlist configuration](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/package.json#L43) on `package.json`. In addition to that, I've fixed deprecation warning because of use of `uglify` option who have changed to `forceAllTransforms`.

* [Enforced Unix newlines](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/.gitattributes) for some files, like [bootstrap does](https://github.com/twbs/bootstrap/blob/master/.gitattributes)

* [Fixed Jest tests](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/package.json#L47).

    * [Added Jest dependencie](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/package.json#L27) who was missing.

    * [Changed](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/tests/Javascript/Example.spec.js#L1) deprecated `shallow` to `shallowMount`

* Made scripts on [package.json](https://github.com/rivajunior/laravel-5-boilerplate/blob/node_optimizations/package.json#L7) work with _Yarn_ and _NPM_, using `$npm_execpath` how as suggested on #1216.
    * The problem is a Yarn warning which says basicaly that it won't work in the future:

       * > warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.

* Removed unnecessary `node_modules/.bin/whatever` path from scripts on `package.json`. See [npm-run-scripts](https://docs.npmjs.com/cli/run-script.html)

### CODE REVIEW

**Comment by rappasoft** [comment]
Great PR. Thanks for listing all the changes with sources, I have no problem with any of this I just need to test it all my self before merging in.

**Comment by rivajunior** [comment]
> Great PR. Thanks for listing all the changes with sources, I have no problem with any of this I just need to test it all my self before merging in.

I forgot to say that I've tested the scripts on my windows 10 (bash, cmd, powershell) and on ubuntu 18.04 (homestead)

**Comment by rappasoft** [comment]
The only difference I see is that font awesome can no longer be used on the backend, I get that coreui uses simple line icons (which is annoying to begin with) but we should still have the option to use them globally. So i'm probably going to modify that.

**Comment by rivajunior** [comment]
> The only difference I see is that font awesome can no longer be used on the backend, I get that coreui uses simple line icons (which is annoying to begin with) but we should still have the option to use them globally. So i'm probably going to modify that.
> 
> Edit: There are actually a few on the backend that don't currently appear because of this, so we have to make it global somewhere.

Don't worry, I'll do that.

I don't have sure, but I think we don't need to use Simple Line Icons. It is used on CoreUI examples, but we not obligated to use it. So if we remove and use only font-awesome, it can be lighter than use two icon fonts.

**Comment by rappasoft** [comment]
I did it already: https://github.com/rappasoft/laravel-5-boilerplate/commit/7b3c896687f81f92c1c1ad7a0f8fb32ca687d563

**Pull request merged**
