### PR TITLE
5.6 js

### PR DESCRIPTION
**Pull request by bingalls**
## JavaScript Testing
Fixes package.json for nodejs v10.0.0. Yarn still needs to catch up
Adds
* Eslint
* Jscsrc
* Jshint
Fixes JavaScript code to pass these tests
Adds editorconfig & testing.md to explain these tests

### CODE REVIEW

**Comment by bambamboole** [comment]
@bingalls why do this PR adds 140000!! new lines of code?

**Comment by bingalls** [comment]
Hmm. @bambamboole  It looks that SCSS files from sibling branch got merged in. I'll remove those. Removing package.lock will reduce the lines, as well.

**Comment by rappasoft** [comment]
Do we really need these tools?

**Comment by bingalls** [comment]
Replaced by 5.1.6_js

**Pull request closed without merging**
