### PR TITLE
Integrate Repository make command.

### PR DESCRIPTION
**Pull request by ruchit-viitorcloud**
Enhancement.
Hello Anthony Rappa,
I have integrate Repository make command, which is helpful to create dynamic repository in any folder along with model name.

Below are the steps for making repository

**Repository Creation:-**
If you want to create "Base Repository" and BaseRepository.php not exist  in  your project at that time, you can execute below command.
`php artisan make:repository BaseRepository -b`

If you want to create repository for any module, you can execute below command
`php artisan make:repository <Name of the Repository>`

If you want to create repository inside "Asset" folder,
`php artisan make:repository Asset\<Name of the Repository>`

If you want to create repository directly inside "Repository" folder, 
`php artisan make:repository <Name of the Repository>`

If you want to create repository with model name, 
`php artisan make:repository <Name of the Repository> --model-name=<Name of the Model>`

Please let me know, if there is change in my pull request.

Thanks.

### CODE REVIEW

**Comment by rappasoft** [comment]
The base repository will exist in this project so not sure thats needed.

**Comment by poseso** [comment]
I see this is more useful for those who wants to generate Model, attribute, relation, scope trait and repository https://github.com/hariadi/laravel-boilerplate-generator

**Comment by rappasoft** [comment]
I don't think this is ready, though we appreciate it. We can use it as a base in the future when we decide the to make this.

**Comment by ruchit-viitorcloud** [comment]
Thanks for that

[image: Ruchit]
Ruchit Patel
Software Developer
<https://in.linkedin.com/in/ruchit-patel-5b852512a>
Direct: +91-7940031384
US: +1-201-203-9313 (TOLL FREE)
Skype: live:ruchit.patel_3
Email: ruchit.patel@viitorcloud.com
<http://www.viitorcloud.com/>
<https://www.facebook.com/viitorcloud.technologies.private.limited>
<https://twitter.com/viitorcloud>
<https://www.linkedin.com/company/viitor-cloud-technologies>
<https://plus.google.com/+Viitorcloud/posts>
Visit our website : www.ViitorCloud.com <http://www.viitorcloud.com/>
Please consider the environment before printing this email

**Pull request closed without merging**
