### PR TITLE
Set admin names on Admin LTE

### PR DESCRIPTION
**Pull request by blomdahldaniel**
As much as I love you and the repo Rappa, I would very much like to not have to change this every other time i clone your repo. 

What do you think?

### CODE REVIEW

**Comment by blomdahldaniel** [comment]
Sorry for not putting them in the same commit, it was such a small change so i did it here threw github and i didnt know how to make it propely..

**Comment by rappasoft** [comment]
I think it should use the access wrapper, you can replace those with access()->user()->name and it should do the same. Then I can merge it in.

**Comment by blomdahldaniel** [comment]
Okey so how and why the access wrappers? Just the syntax you would like in your reop or is there something other more useful in mind of that?

**Comment by rappasoft** [comment]
The access wrapper provides access to the user control management system, plus it would keep it consistent. It is literally Auth::user()->name anyway. But with access you can do access()->can() access()->hasRole(), etc.

**Comment by blomdahldaniel** [comment]
Aah, I see! Great, now I created a new pull request with the 2 file changes in the same branch.

**Pull request closed without merging**
