### PR TITLE
Using PHP-CS-Fixer the right way

### PR DESCRIPTION
**Pull request by rivajunior**
# Is this a fix, enhancement or language pack?

This is a enhancement

The past configuration of [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) didn't do much and [StyleCI](https://styleci.readme.io/) haved always to do the work.

Now I've looked on StyleCI  [Laravel presets](https://styleci.readme.io/docs/presets#section-laravel) (outdated by the way) and configurate PHP-CS-Fixer by myself.

I must warn you that some configurations are a little opinionated, so I decided to leave the first use of the fixer for you @rappasoft, because a lot of files will be changed and you will be able to decide which configuration to keep.

PS: You can check some examples on [php-cs-fixer-configurator](https://mlocati.github.io/php-cs-fixer-configurator/#)

### CODE REVIEW

**Comment by rappasoft** [comment]
Just curious what makes StyleCI's current Laravel presets outdated?

**Comment by rivajunior** [comment]
Take it by example:

* **align_phpdoc** should be **align_multiline_comment**

* **blank_line_before_return** is DEPRECATED

    * > An empty line feed should precede a return statement. DEPRECATED: use blank_line_before_statement instead.

From [PHP-CS-Fixer Usage Documentation](https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage)

**Comment by rivajunior** [comment]
@rappasoft have you seen how the code goes with these settings?

If you want I can automatizate it with [Husky](https://github.com/typicode/husky), so everybody who works on the code will normalize the code durring commit, on their own machines.

**Comment by rappasoft** [comment]
At first glance i dont have any issue with what i'm seeing in the 395 files that it modified.

PHPStorm 2019.1 added native support to code cleanup so i'm going to run both and see how they differ.

Screen Shot 2019-03-31 at 22 12 20

**Pull request merged**
