### PR TITLE
Feature tests

### PR DESCRIPTION
**Pull request by safoorsafdar**
FrontEnd/testHome
FrontEnd/Access/test_user_can_see_auth_register
FrontEnd/Access/test_user_can_see_auth_login
FrontEnd/Access/test_redirect_to_login_if_i_try_to_view_dashboard_without_logging_in
FrontEnd/Access/test_can_create_an_account
FrontEnd/Access/test_user_can_login_without_remember_me
FrontEnd/Access/test_user_can_login_with_remember_me

### CODE REVIEW

**Comment by rappasoft** [comment]
Hmm i'm trying to think of an easy way to merge this..

**Comment by safoorsafdar** [comment]
:) I was in the same boat...

**Comment by safoorsafdar** [comment]
I think you only need to merge commit "7bbead2"

**Comment by rappasoft** [comment]
Would you mind if I manually merged this in? It would just be avoid a ton of conflicts. I'll still give you credit.

**Comment by safoorsafdar** [comment]
Not a big problem... But I believe need to define specific way to contribute under wiki.

**Comment by safoorsafdar** [comment]
Can you provide me features list we should test under Backend/Access? So I will complete them one by one in my spare time

**Comment by rappasoft** [comment]
Manually merged them in, one was erroring due to SwiftMailer so I put a todo. Thank you for the help!

**Pull request closed without merging**
