### PR TITLE
Include pace js

### PR DESCRIPTION
**Pull request by nasirkhan**
installed Pace directly from the github by adding "pace": "github:HubSpot/pace#v1.0.2" in pacage.json. 

`yarn build` passed successfully. but shill not showing.

### CODE REVIEW

**Comment by rappasoft** [comment]
Hmm but if you run npm run dev you still get build errors. Thats the problem.

**Comment by nasirkhan** [comment]
i am not getting any error now. `npm install` again and `npm run dev`. if you check the commit i did not change much.

**Comment by rappasoft** [comment]
I get this error, even though the actual file exists in node modules: 

screen shot 2017-09-25 at 09 29 25

**Comment by bloggervista** [comment]
i guess it is due to require('../../../../node_modules/pace-js/pace.min');  cannot we do ./node_modules/pace-js/pace.min

**Comment by rappasoft** [comment]
I tried both, same error. File exists I don't know why it's not picking it up.

**Comment by nasirkhan** [comment]
i was getting the same error and then googled a bit, and found that added "
pace": "github:HubSpot/pace#v1.0.2", and then 'yarn' and 'yarn dev' and it
stopped showing the error. I will check again and inform you the updates.




--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by nasirkhan** [comment]
i am not getting any error. removed the `node_modules` and then ran the `yarn` and `yarn dev`. build passed successfully.

**Comment by bloggervista** [comment]
nasirkhan you may be from windows. It may be cross platform issue.

Rappasoft lets not mind this error . We can download pace.js and use mix.copy for now and we can think its solution later.

**Comment by nasirkhan** [comment]
@bloggervista i am not running windows. Just google the error and you will find that a lots of other people faced the same issue. 

You are right it is not a show stopper and we can add this later. 

for discussing the upgrade plan we were using the slack channel (https://laravelboilerplate.slack.com/messages/C75A9UJBC/), lets use that more actively.

**Comment by rappasoft** [comment]
Fixed thanks!

**Pull request closed without merging**
