### PR TITLE
Admin index. (redirect)

### PR DESCRIPTION
**Pull request by lloricode**
### Fix
Additional route for admin index,

### CODE REVIEW

**Comment by rappasoft** [comment]
How about just a redirect?

**Comment by lloricode** [comment]
@rappasoft it make sense if we add a route/url for index in admin to easy viisit in admin like
`myweb.com/admin`

**Comment by lloricode** [comment]
just like a normal frontend index
```php

Route::get('/', 'HomeController@index')->name('index');
Route::get('dashboard', 'DashboardController@index')->name('dashboard');

```

**Comment by rappasoft** [comment]
Right what i'm saying is just redirect /admin to /admin/dashboard instead of creating more controller methods and breadcrumbs

Route::redirect('/here', '/there', 301);

**Comment by lloricode** [comment]
hmm, new idea to me, i try now

**Comment by lloricode** [comment]
@rappasoft, is this right?

**Pull request merged**
