### PR TITLE
Remove hardcoded value (21) in PermissionDependencyTableSeeder.php

### PR DESCRIPTION
**Pull request by kdhana**
Handles future issues related to #276 and #250.

### CODE REVIEW

**Comment by blomdahldaniel** [comment]
Hm.. I think this was fixed yesterday with #281 or do you think that this PR does something else than that.

**Comment by error500** [comment]
@kdhana  did an elegant solution

**Comment by kdhana** [comment]
@blomdahldaniel
This is a minor improvement and could be easily ignored.
Hardcoding values should always be avoided (even in such trivial scenarios).

**Comment by blomdahldaniel** [comment]
Great job! @kdhana 
I am not so familiar with this issue so I will let @rappasoft take a look at it.

**Comment by rappasoft** [comment]
I like it.

**Pull request merged**
