### PR TITLE
Danish translation

### PR DESCRIPTION
**Pull request by steenrabol**
Hi

Herby the Danish translation

### CODE REVIEW

**Comment by blomdahldaniel** [comment]
Great job my Scandinavian fellow! ;) 
If you could remove the following files from your commits we can merge it in:

* `.gitignore`
*  `.phpintel/ac0334477749c76fd2dd376a1fcc339e`
* `.phpintel/index`
* `laravel-start.komodoproject`

**Comment by steenrabol** [comment]
Hi
Git is my my strength :)

I have tried to romev the files, let me know if it is okay now.

**Comment by blomdahldaniel** [comment]
Great! But I see now that I maybe was a bit unclear. You should not remove the entire `.gitignore` just remove the changes that you had done in the first commit.

I suggest  that you copy the `.gitignore` from  this repo straight up, paste it in to your repo, add it and commit the file. Then you are good to go! :D

**Comment by rappasoft** [comment]
I pulled this, I don't know why it didn't merge from here. So i'll just close it. Thanks @steenrabol!

**Pull request closed without merging**
