### PR TITLE
tables timestamp fields : removed unecessary default values

### PR DESCRIPTION
**Pull request by error500**
This defaults value is not available in postgres
$table->timestamp('updated_at')->default('0000-00-00 00:00');
And 
$table->timestamp('updated_at')
will anyway push the  default value through eloquent save function.
I remove also the default on field created_at for homogeneity reasons

### CODE REVIEW

**Comment by blomdahldaniel** [comment]
Then, if we are safe to go back to the pure laravel setting for this I think it is better looking to use the laravel `$table->timestamps()`

So I suggest that we change this in all migrations as well:
```diff
- $table->timestamp('created_at');
- $table->timestamp('updated_at');
+ $table->timestamps();
```

**Comment by rappasoft** [comment]
There was an issue with the default timestamps() method, that's why it was changed. I just don't remember exactly what it was.

**Comment by rappasoft** [comment]
I believe the issue was both columns were getting an on update current timestamp attribute for no reason.

**Comment by blomdahldaniel** [comment]
Hm.. @error500 the last commt a9a5599 maybe should be in its own PR and not in this one?
It looks interesting though

**Comment by error500** [comment]
@blomdahldaniel yes, i'm a github & pull request newbie...

**Comment by blomdahldaniel** [comment]
No worries. Then you fit in with the rest of us. :)

**Comment by error500** [comment]
All my commits on branch master will go on the same PR ? is that the reason i should create 1 branch for each PR purpose ?

**Comment by blomdahldaniel** [comment]
Yep exactly! :)
One branch for every pull request. Preferably named in a similar way as the PR.

**Comment by rappasoft** [comment]
Closing this since there are new separate requests.

**Pull request closed without merging**
