### PR TITLE
Changing the AuthController to send the links of active social networ…

### PR DESCRIPTION
**Pull request by andersondeoliveiramachado**

### CODE REVIEW

**Comment by rappasoft** [comment]
Actually, I think it's fine for now. I'm going to go through the project in its entirety and refactor at some point when I redo the access library. Nice work.

**Comment by andersondeoliveiramachado** [comment]
Thanks for accepting. I am new to laravel. Now I will try to make a simple crud and enter the menu. What do you think of the idea? maybe the tables countries and states frontend.layouts.master

**Comment by rappasoft** [comment]
I'm not following. What exactly do you want to change?

**Comment by andersondeoliveiramachado** [comment]
In fact would not change but add.

Two tables in the database: countries and states

And put a menu on the backend.

entries
   countries
   states

Can use the package:

https://github.com/mitulgolakiya/laravel-api-generator

**Comment by rappasoft** [comment]
That may be a little overkill for this project. Those are just examples to extend the form helpers since they were removed in laravel 5.0.

**Pull request merged**
