### PR TITLE
Switch from SweetAlert to SweetAlert2

### PR DESCRIPTION
**Pull request by limonte**
I would like to propose to switch from SweetAlert to [SweetAlert2](https://github.com/limonte/sweetalert2) - the supported fork of SweetAlert. The original reason for creating SweetAlert2 is inactivity of SweetAlert: https://stackoverflow.com/a/27842854/1331425 

### Reasons to switch:

1. Accessibility (WAI-ARIA) - SweetAlert2 is fully WAI-ARIA compatible and supports all popular screen-readers. Accessibility is a must in 2017, there are a lot of explanatory and tech articles, but this one is truly inspirable: [Software development 450 words per minute](https://www.vincit.fi/en/blog/software-development-450-words-per-minute/)

2. Better buttons contrast is a huge advantage for all users especially for users with vision disabilities. 

2. Better support, average time to resolve an issue:

   - SweetAlert: 
   - SweetAlert2: 

3. Less LoC for the same functionality

4. SweetAlert2 is more popular that SweetAlert:

   - SweetAlert: 
   - SweetAlert2: 

--- 

There are `swal` usages in `frontend.js` and `backend.js`. If needed, I can regenerate them as well to contain SweetAlert2. 

---

PS. I'm the [active Laravel user](https://stackoverflow.com/search?tab=votes&q=user%3a1331425%20%5blaravel%5d) and I want to thank for the awesome work you are doing! Keep it up! :muscle:

### CODE REVIEW

**Comment by rappasoft** [comment]
Would be happy to pull if you want to convert it over. This looks like you've done that? Or is there something else that needs to be done?

**Comment by limonte** [comment]
Bumped `public/js/frontend.js`, `public/js/backend.js`, and `public/mix-manifest.json` :+1: Take a look

**Comment by rappasoft** [comment]
Hmm i'm getting a swal is not defined error.

**Comment by limonte** [comment]
> Hmm i'm getting a swal is not defined error.

Should be fixed now

**Comment by rappasoft** [comment]
Works, will merge into development.

**Pull request merged**
