### PR TITLE
Fixed models __construct method

### PR DESCRIPTION
**Pull request by soulshockers**
Models parent constructor should be called in case child constructor is defined.

### CODE REVIEW

**Comment by rappasoft** [comment]
Do you have an example as to why?

**Comment by soulshockers** [comment]
/** @var \App\Models\Access\Role\Role $role */
$role->permissions()->create(['group_id' => 1, 'name' => 'test_name', 'display_name' => 'test_display_name']);
//or
Role::create([...attributes...]);
All attributes passed to create method will be lost.

**Comment by rappasoft** [comment]
Are you sure? You should be able to use ```$role->permissions()->create``` without a problem?

**Comment by soulshockers** [comment]
Of course I'm sure. 
method $role->permissions()->create is method of Illuminate\Database\Eloquent\Relations\BelongsToMany which call newInstance method of Illuminate\Database\Eloquent\Model which create instance of Permission model by passing $attributes array to our model __construct method. That's why parent constructor of every model should be called.

**Pull request merged**
