### PR TITLE
Translation for "sv"  Swedish/Svenska

### PR DESCRIPTION
**Pull request by blomdahldaniel**
Here is my translation for the Swedish language package.

### CODE REVIEW

**Comment by blomdahldaniel** [comment]
@rappasoft 
I am starting to wonder if you should start the language pack as a separate repo? If the language packs will keep on rolling in that might be a nice thing? So that you can pull in what ever language folders you would like.

**Most importantly** It could be easier to keep track of when changes are made, keep version info so that every translator can have an quick overview of the latest update and then add the needed translation. Just a thought.

**Comment by rappasoft** [comment]
Yeah probably a good idea. I have a lot of changes in english right now that I cant convert to the other two properly.

**Comment by blomdahldaniel** [comment]
Exactly the reason of why that could be held as a different project so it is easier to maintain and work with. 

And I must say, you should not spend too much time trying to convert or Google translate anything. You should be coding man! :p It is better to have a readme (in that project) that shows the status of each language pack. So after an update to the english one, all the other languages gets marked "unstable" or something until an update of the pack is pulled in.

But in case of such a repo a changelog would be verry important so that all the people that want to translate can do that easily. I'll bet most of the people who has contributed with language packs so far can keep on helping with that.

**Comment by rappasoft** [comment]
I'm gonna pull this is as soon as i'm done with the access feature.

**Comment by blomdahldaniel** [comment]
Hm... When i change APP_LOCALE to `APP_LOCALE=sv` it doesnt translate.. Do I need to register the sv folder or have I just missed some translation handler when i have done my manual updates of your repo?

**Comment by blomdahldaniel** [comment]
Dont mind my last comment, I had switched to english trew the language selector in the `backend/header`. So I added Swedish to that dropdown now as well.

**Comment by rappasoft** [comment]
This is probably going to cause some conflicts if I merge now since I edited the language files in the last release and it seems like you changed some of the other language files too. If it was just new sv pack it would work.

**Comment by rappasoft** [comment]
Is there a way to just recommit with the language files? It seems the changes to the other languages are commit duds that aren't needed. And I will add the language to the dropdown. Let me know otherwise I can cherry pick one by one.

**Comment by blomdahldaniel** [comment]
Okey, the changes to the other languages was that I added the word Swedish in the language array for the other languages. I will try to remove them. 

What are your thoughts/plans on the dedicated language repo?

**Comment by rappasoft** [comment]
It's a good idea because right now all 4 packs are different because I added a lot in the new access feature, and just added the english versions to all the packs. So by default yours will be missing a bunch. I don't know how to go about it.

**Comment by blomdahldaniel** [comment]
Yeah, I'll have to go over them again from bottom to top.

I would say only include english in this repo, create a new repo and reference to that here in the readme under *Localization* or *Language*.

Then create a new repo thats called /laravel-5-boilerplate-languages (or something like that)
Then handle all the language stuff there. Show status in readme so users can keep track in the readme. Something like this:

# larave-5-boilerplate-localization
Language packages for the repo [larave-5-boilerplate](https://github.com/rappasoft/laravel-5-boilerplate)

## Current language version: 1.4

### Currently uppdated languages:
- [x] it - Italian
- [x] pt-BR - Brazille

### Currently outdated languages:
- [ ] sv - Swedish (Last updated, [1.3](#))
- [ ] de - German (Last updated [1.2](#))

## Changelog
*  **1.4** - the new ACL system
    ````
    // foo.php
    "key_to_trans" => "English version of the new trans",
   "second_new_key" => "Second new translation"

   //bar.php
   "changed_key_in_bar" => "The translation to bar"
      
    `````
*  **1.3** - added hello stuff
    ````
    // hello.php
    "hello_you" => "English hello Sir!",
   "cup_of_tea" => "A cup of te perhaps?"
      
    `````
*  **1.2** - added the entire `hello.php` file
  

The language versioning can be completely free from the project version number. 
So set up version and changelog for the languages here?
The repo holds nothing but the language folders and the readme.

This way, people can see quite easy what they need to do to update their languages?
And that way you keep the main repo clean from the localization stuff with updates and changes?

**Comment by blomdahldaniel** [comment]
What do you think about that?

And now, from this point, start fresh with all the languages. Start at 1.0 and only set all the languages as outdated. And then start to keep track from here on?

**Comment by dgallinari** [comment]
:+1: !!!

Totally agree Daniel! We will for sure help with further translations on pt-Br whenever necessary

**Comment by blomdahldaniel** [comment]
Great! @dgallinari 
I should maybe check with our italian as well: @vjandrea 

And if we start fresh with the language version it will make it easier to add new stuff to the next update.

**Comment by vjandrea** [comment]
I'm in!

Definitely a + 1




Il giorno lun 21 set 2015 alle ore 19:52 Daniel Blomdahl <
notifications@github.com> ha scritto:

**Comment by rappasoft** [comment]
I am going to manually merge this in file by file to make sure it doesn't conflict anything. Hope you don't mind. Also, people have been translating views/backend/lang/xx/welcome.blade.php if you wouldn't mind.

**Pull request closed without merging**
