### PR TITLE
Master

### PR DESCRIPTION
**Pull request by amamarul**
Hello, I implemented the new Translation Strings Localization, I think you can already delete "JSON Lang Files (Maybe) - Looked at this, was much more involved than I first thought so will probably leave." In https://github.com/rappasoft/laravel-5-boilerplate/issues/609.
Also I am finishing a package to manage the strings that I hope will be uploaded soon.

It is necessary to arrange the translation of the roles in the file
"resources/views/backend/access/index.blade.php" line 35
It's working but I think we need to improve it

### CODE REVIEW

**Comment by rappasoft** [comment]
Wow thats a lot of work thanks! I did want to do this too. I will probably take your commits and merge them in file by file instead of all at once since it's a lot though.

**Comment by amamarul** [comment]
Hello!
Yes, it was a lot of work.
I was following the migration to L5.4 and I was testing, I really like your project.
When I read that you would like the Strings I saw that it was a lot and I think it is a very good new tool and very useful. For this reason I developed a package to manage the strings of the languages, I think it is getting very good, for that reason I was able to automatically generate with my package the json files.
Then I had to change all trans ('...') one by one.
I'm really glad you like my job.
I have been using BP in a project since the L5.2 version and I really like it.
I appreciate your work very much and I value it very much, for that reason I want to contribute to the measure of my possibilities.
Maybe we can do the tests in the branch development and among all we can go fixing the errors that may be. I particularly did tests but hey, you are the expert
Sorry for my English is not my native language.
regards
Maru

**Comment by amamarul** [comment]
I already uploaded my package, I would love to hear your opinion. 
https://github.com/amamarul/laravel-json-locations-manager
Maru

**Comment by rappasoft** [comment]
I'm going to download this and save it, it's been too long and too many changes to let github merge. We may go to json lang files in the future. Thanks for all the hard work!

**Pull request closed without merging**
