### PR TITLE
Arabic Language and RTL Support

### PR DESCRIPTION
**Pull request by elbadawy**
Hi,

First of all, i want to thank you and all the contributors in this project, it's one of the best boilerplate projects for Laravel.

As i usually use this boilerplate in many projects that requires an addition of Arabic language, and because of the Arabic language is one of the languges that requires an RTL (Right to Left) layout, i added the Arabic translation and also i made some changes to add the RTL layouts in the frontend and the backend.

This is a list of the changed files and folders for easy review:
* Arabic translation folder in `'resources/lang/ar/'`
* Added the Arabic language to the manu for all the other languages.
* Added a new folder in` 'resources/assets/css/rtl'` that includes the` 'bootstrap-rtl.css'` file that contains the necessary override classes to change the direction of the Bootstrap framework from LTR (Left to Right) to RTL (Right to Left).
* Added a line to` 'views/frontend/layouts/master.blade.php'` to check if the selected language is Arabic so it can add the` 'rtl.css'` file to the layout.
* Added the all necessary codes to combine all the RTL stylesheets files in `'gulpfile.js'`.
* **Notice:** Added 'gulp-rtlcss' npm package and use it in` 'elixir-extensions.js'` file to use it to automatically change the direction of the backend layout to RTL.
* Added check for the selected language in `'views/backend/layouts/master.blade.php'` to add the necessary RTL override stylesheets to the backend's layout.

## Screenshots

screencapture-localhost-laravel_boilerplate_arabic_dev-public-admin-access-users-1468223584728
screencapture-localhost-laravel_boilerplate_arabic_dev-public-admin-dashboard-1468223554337
screencapture-localhost-laravel_boilerplate_arabic_dev-public-admin-log-viewer-1468223636072
screencapture-localhost-laravel_boilerplate_arabic_dev-public-admin-log-viewer-logs-1468223703375
screencapture-localhost-laravel_boilerplate_arabic_dev-public-dashboard-1468223452436
screencapture-localhost-laravel_boilerplate_arabic_dev-public-dashboard-1468223506915
screencapture-localhost-laravel_boilerplate_arabic_dev-public-login-1468223333299
screencapture-localhost-laravel_boilerplate_arabic_dev-public-password-change-1468223488051
screencapture-localhost-laravel_boilerplate_arabic_dev-public-register-1468223378782

### CODE REVIEW

**Comment by rappasoft** [comment]
Was this based off version 2 or 3?

**Comment by elbadawy** [comment]
Version 3

**Comment by rappasoft** [comment]
This is a lot to merge in, I have to figure out a way to do this without unnecessary code because the amount of people that are going to use it is far less than those who will.

So in order to keep it tidy.

**Comment by rappasoft** [comment]
I have implemented this, but I did it manually so I could come up with a way to not have it Arabic specific. I'll close this when I merge mine but obviously give you credit in the log.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-5-boilerplate/commit/ae73cc470bd9423bced77d0aeef71eb07f76ff3d

**Pull request closed without merging**
