### PR TITLE
Eager loading on History renderType & Ajax History 

### PR DESCRIPTION
**Pull request by HilmanAnshori**
Change lazy loading on History repository when accessing renderType to eager loading, as requested from [my issue](https://github.com/rappasoft/laravel-5-boilerplate/issues/451).

### CODE REVIEW

**Comment by HilmanAnshori** [comment]
I'm also adding history limit by skip and take (not paginate) and render it using ajax call from view.

demo : 
<a target="_blank" href="http://www.youtube.com/watch?feature=player_embedded&v=JIAiJtNKkDY" target="_blank">Laravel 5 Boilerplate Ajax History</a>

BR,

**Comment by rappasoft** [comment]
This is a great PR, but my only concern is what if people don't want a auto growing history section, or the history section is not the last item on the page.

What if people wanted just regular pagination with a ?history=1,2,3,4 in the url or something like that.

**Comment by HilmanAnshori** [comment]
> This is a great PR, but my only concern is what if people don't want a auto growing history section, or the history section is not the last item on the page.

They can still use original function render with no parameters if they want to display all histories or 
```php
history()->render(0,10)
```
for example if they want to limit latest 10 histories. Ajax auto growing is just an example to use limiting by skip and take. And if the history section is not in the last item on the page and they want auto growing history, they can implement ajax call from js event that suite to their need.


> What if people wanted just regular pagination with a ?history=1,2,3,4 in the url or something like that.

I haven't make changes to implement regular pagination yet.  
_?history=1,2,3,4_ are history ids?

**Comment by rappasoft** [comment]
history would be "page", just a different name incase theres other page parameters.

**Comment by HilmanAnshori** [comment]
ok, i'll try to use paginate

**Comment by rappasoft** [comment]
Basically as simple, with the lease amount of code possible. Since this is just a boilerplate.

**Comment by HilmanAnshori** [comment]
```php
history()->render();
// return all records

history()->render(10);
// return latest 10 records

history()->render(false, true);
// return paginated, 10 per page, page number query string "history"

history()->render(false, true, 15);
// return paginated, 15 per page, page number query string "history"

history()->render(false, true, 15, 'pagenumber');
// return paginated, 15 per page, page number query string "pagenumber"
```
Also add renderJson to history repository for auto growing :D

**Comment by rappasoft** [comment]
Thank you for this big and generous addition, however at this point I think it is too verbose to be added as a 'boilerplate' feature. I have implemented pagination by default instead.

Again thank you, maybe it will be considered in the future.

**Pull request closed without merging**
